// default package
// Generated 29/11/2017 09:38:28 AM by Hibernate Tools 5.2.6.Final

/**
 * Usuario generated by hbm2java
 */
public class Usuario implements java.io.Serializable {

	private Integer idusuario;
	private String nombre;
	private String correo;
	private String contrasenia;
	private String cel;

	public Usuario() {
	}

	public Usuario(String nombre, String correo, String contrasenia, String cel) {
		this.nombre = nombre;
		this.correo = correo;
		this.contrasenia = contrasenia;
		this.cel = cel;
	}

	public Integer getIdusuario() {
		return this.idusuario;
	}

	public void setIdusuario(Integer idusuario) {
		this.idusuario = idusuario;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	public String getContrasenia() {
		return this.contrasenia;
	}

	public void setContrasenia(String contrasenia) {
		this.contrasenia = contrasenia;
	}

	public String getCel() {
		return this.cel;
	}

	public void setCel(String cel) {
		this.cel = cel;
	}

}
